server:
  port: 9911

spring:
  application:
    name: wbw-cloud-service-discovery

logging:
  file: logs/${spring.application.name}.log
  level:
    root: info
eureka:
  client:
    #    注册自己
    register-with-eureka: false
    #    获取注册列表
    fetch-registry: false
  server:
    #    同步为空等待时间
    wait-time-in-ms-when-sync-empty: 5